"""Dropped user_id from players

Revision ID: 302ff2e18ba1
Revises: 4257e07355cc
Create Date: 2025-05-07 17:28:21.952016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302ff2e18ba1'
down_revision = '4257e07355cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('fk_players_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_players_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
