"""added Session model

Revision ID: 402d1b5849ae
Revises: 9efbfe0b2c3c
Create Date: 2025-05-06 14:37:04.887282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402d1b5849ae'
down_revision = '9efbfe0b2c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_sessions_game_id_games')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
