"""Added summary to Player model

Revision ID: 9efbfe0b2c3c
Revises: 634c2bd8bc9b
Create Date: 2025-05-06 14:11:47.771265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efbfe0b2c3c'
down_revision = '634c2bd8bc9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('summary')

    # ### end Alembic commands ###
